#-------------------------------
# General Site Settings

title: D-BI | Davis on BI
description:  Data Analytics and Microsoft BI by DavisZHANG 
baseurl: "" 
url: "https://d-bi-tech.github.io/" 


#-------------------------------
# About Section
author-name:   Davis ZHANG
author-avatar: 09.jpg


#-------------------------------
# Contact links
linkedin:  https://www.linkedin.com/in/davis-zhang/ 
zhihu:   https://zhihu.com/people/zhang-zhe-hong-01/posts 
# playstation: https://my.playstation.com/profile/KEID-MG
wordpress: https://davisisland.wordpress.com/
email-address: daviszhang@189.cn

#-------------------------------

# RSS
RSS: true


# Netease settings
netease_comment: false

gitalk:
    enable: true
    owner: DavisZHANG-BlogOnly
    repo: ForBlogOnly
    clientID: 81594f9ebba24848f9be
    clientSecret: 4c1babae593e874b16d25a3cded87646d71db3d4
    admin: DavisZHANG-BlogOnly
    distractionFreeMode: true




#-------------------------------
# Google Analytics
google-analytics: UA-153204823-1


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
