#-------------------------------
# General Site Settings

title: D-BI | Davis on BI
description: Galada is an easy and simple theme for Jekyll. Dark colors, give it a special exquisite look. A careful approach to design and features make it an ideal solution for a personal blog. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://d-bi-tech.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Natali Anderson
author-avatar: 09.jpg


#-------------------------------
# Contact links
linkedin:  https://www.linkedin.com/in/davis-zhang/ 
zhihu:   https://zhihu.com/people/zhang-zhe-hong-01/posts 
instagram: https://www.instagram.com/ 
pinterest: https://www.pinterest.com/


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Disqus settings

# disqus_username: Lucy

# Netease settings
netease_comment: false

gitalk:
    enable: true
    owner: DavisZHANG-BlogOnly
    repo: D-BI-TECH.github.io
    clientID: 0cafbeac3e41c55928b0
    clientSecret: f1e390e070e04539e1c6254ff4647ad95d9068d3
    admin: D-BI-TECH
    distractionFreeMode: true




#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
